# Site settings
title: Weekly Robotics Newsletter | Go, Robots!
description: "Weekly Robotics Newsletter - stay up to date on state of the art robotics, drones, space, open source projects and research."
url: "https://weeklyrobotics.com"
author:
  name: "Weekly Robotics"
  email: "contact@weeklyrobotics.com"
  url: "https://weeklyrobotics.com"

exclude: ["_templates", "CNAME", ".gitignore", "tools"]

# Build settings
encoding: utf-8
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate_path: /page:num/

#SEO
locale: en_US

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.1"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
paginate: 1
