# Site settings
title: Weekly Robotics
description: "Robotics content aggregator with handpicked resources every week"
url: "http://weeklyrobotics.com"
author:
  name: "Weekly Robotics"
  email: "contact@weeklyrobotics.com"
  url: "http://weeklyrobotics.com"

exclude: ["_templates", "CNAME", ".gitignore"]

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 4
paginate_path: /page:num/

#SEO
locale: en_US

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.1"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
